version: '2'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      
    volumes:
      - /data/www/build:/data/www/build
      - /data/www/audio:/data/www/audio
    links:
      - web:web

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app
    command: /usr/local/bin/gunicorn -w 2 -b :8000 autoapp:app
    links:
      - postgres:postgres
    depends_on:
      - "postgres"

  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - postgres-data:/var/lib/postgres/data
    expose:
      - "5432"

volumes:
  postgres-data:
    driver: local